### ISSUE TITLE
能不能整合成一个jar插件？

### ISSUE THREAD

**Issue by ABT98421** [WhiteMagic2014/WMagicBotR#44]
已经部署Mirai Console了

**Comment by WhiteMagic2014** [comment]
啊..这个项目不是按照Mirai Console的插件约定写的....
这个项目本身是框架的整合 指令开关等 都是一些方便开发的设计。
Mirai Console 的插件更多是业务上的功能扩展把...
(我也不太了解，还没研究过Mirai Console 插件开发约定，有时间我去了解一下 目前只能说 没办法做成插件了)
